"""Execute KQL commands generated by ADX Schema Builder V2 against local Docker ADX emulator."""
import json, urllib.request, sys, time

ADX_URL = "http://localhost:8080/v1/rest/mgmt"
DB = "NetDefaultDB"

def run_kql(name, csl):
    """Execute a single KQL management command and return success/failure."""
    payload = json.dumps({"csl": csl, "db": DB}).encode()
    req = urllib.request.Request(ADX_URL, data=payload, headers={"Content-Type": "application/json"})
    try:
        resp = urllib.request.urlopen(req, timeout=30)
        data = json.loads(resp.read())
        # Check for errors in response
        if "Exceptions" in data and data["Exceptions"]:
            print(f"  WARN: {data['Exceptions']}")
            return False
        return True
    except Exception as e:
        print(f"  ERROR: {e}")
        return False

def validate_tables():
    """Return list of table names in database."""
    payload = json.dumps({"csl": ".show tables", "db": DB}).encode()
    req = urllib.request.Request(ADX_URL, data=payload, headers={"Content-Type": "application/json"})
    resp = urllib.request.urlopen(req, timeout=10)
    data = json.loads(resp.read())
    return [row[0] for row in data["Tables"][0]["Rows"]]

def validate_functions():
    """Return list of function names in database."""
    payload = json.dumps({"csl": ".show functions", "db": DB}).encode()
    req = urllib.request.Request(ADX_URL, data=payload, headers={"Content-Type": "application/json"})
    resp = urllib.request.urlopen(req, timeout=10)
    data = json.loads(resp.read())
    return [row[0] for row in data["Tables"][0]["Rows"]]

# ── STAGING TABLE ──
staging_cmds = [
    ("Netskope_Raw - Create Table",
     '.create table Netskope_Raw (TimeGenerated:datetime, StreamType:string, RawData:dynamic)\n    with (folder="Netskope")'),
    ("Netskope_Raw - Create Mapping",
     """.create table Netskope_Raw ingestion json mapping "Netskope_Raw_Mapping" '[{"Name":"TimeGenerated","Source":"TimeGenerated","Transform":"DateTimeFromUnixMilliseconds"},{"Name":"StreamType","Source":"StreamType"},{"Name":"RawData","Source":""}]'"""),
]

# ── TYPED TABLES (from tool output) ──
# Load from JSON file if provided, otherwise use inline
commands_file = sys.argv[1] if len(sys.argv) > 1 else None

if __name__ == "__main__":
    print("=" * 60)
    print("ADX Schema Builder V2 -> Docker ADX Emulator")
    print(f"Target: {ADX_URL} / {DB}")
    print("=" * 60)

    # Phase 1: Staging
    print("\n-- PHASE 1: Staging Table --")
    for name, cmd in staging_cmds:
        print(f"\n[RUN] {name}")
        ok = run_kql(name, cmd)
        print(f"  {'OK' if ok else 'FAILED'}")

    # Validate staging
    tables = validate_tables()
    print(f"\n  Validation: {len(tables)} table(s) exist: {tables}")

    if commands_file:
        with open(commands_file) as f:
            typed_cmds = json.load(f)
    else:
        print("\nNo typed commands file provided. Pass JSON file as argument.")
        sys.exit(0)

    # Phase 2: Typed Tables
    print(f"\n-- PHASE 2: Typed Tables ({len(typed_cmds)} commands) --")
    ok_count = 0
    fail_count = 0
    for i, entry in enumerate(typed_cmds):
        name = entry["name"]
        cmd = entry["cmd"]
        print(f"\n[{i+1}/{len(typed_cmds)}] {name}")
        ok = run_kql(name, cmd)
        if ok:
            ok_count += 1
            print(f"  OK")
        else:
            fail_count += 1
            print(f"  FAILED")

    # Final validation
    print("\n" + "=" * 60)
    print("FINAL VALIDATION")
    print("=" * 60)
    tables = validate_tables()
    functions = validate_functions()
    print(f"Tables:    {len(tables)}")
    print(f"Functions: {len(functions)}")
    print(f"Commands:  {ok_count} OK, {fail_count} FAILED out of {ok_count + fail_count}")
    print(f"\nTables: {', '.join(sorted(tables))}")
    print(f"\nFunctions: {', '.join(sorted(functions))}")
